# Travis CI
sudo: false
language: ruby
rvm:
- 2.3.1
- 2.3.0
matrix:
  include:
    - rvm: 2.2.5
      env: BUNTO_VERSION=3.0.0
env:
  matrix:
    - BUNTO_VERSION=3.0.0
    - BUNTO_VERSION=3.2.1
branches:
  only:
    - master
before_script:
  - chmod a+x script/bootstrap
  - chmod a+x script/cibuild
  - chmod a+x script/rebund
  - chmod a+x script/release
script: script/cibuild
notifications:
  email:
    on_success: never
    on_failure: change
